export const PRODUCTOS_CONST = [
  {
    "id": 1,
    "marca": "Nike",
    "nombre": "Toalla Deportiva Microfibra",
    "descripcion": "Toalla ultra absorbente de secado rápido, ideal para entrenamientos intensos.",
    "precio": 2500,
    "stock": 120,
    "imagen": "https://example.com/img/toalla-microfibra.jpg",
    "categoria": "toallas",
    "descuento": 10
  },
  {
    "id": 2,
    "marca": "Nike",
    "nombre": "Mancuerna Hexagonal 5kg",
    "descripcion": "Mancuerna de goma antideslizante con agarre ergonómico.",
    "precio": 5500,
    "stock": 50,
    "imagen": "https://example.com/img/mancuerna-5kg.jpg",
    "categoria": "mancuernas",
    "descuento": 5
  },
  {
    "id": 3,
    "marca": "Nike",
    "nombre": "Proteína Whey Chocolate 1kg",
    "descripcion": "Suplemento proteico para recuperación y aumento muscular.",
    "precio": 9500,
    "stock": 80,
    "imagen": "https://example.com/img/proteina-whey-chocolate.jpg",
    "categoria": "proteinas",
    "descuento": 15
  },
  {
    "id": 4,
    "marca": "Nike",
    "nombre": "Guantes de Entrenamiento Pro",
    "descripcion": "Guantes acolchados con ventilación y agarre reforzado.",
    "precio": 3200,
    "stock": 75,
    "imagen": "https://example.com/img/guantes-pro.jpg",
    "categoria": "guantes",
    "descuento": 0
  },
  {
    "id": 5,
    "marca": "Nike",
    "nombre": "Colchoneta Yoga Antideslizante",
    "descripcion": "Superficie antideslizante para yoga, pilates o estiramientos.",
    "precio": 4800,
    "stock": 30,
    "imagen": "https://example.com/img/colchoneta-yoga.jpg",
    "categoria": "accesorios",
    "descuento": 20
  },
  {
    "id": 6,
    "marca": "Nike",
    "nombre": "Cinturón de Fuerza Neoprene",
    "descripcion": "Soporte lumbar para levantamiento de peso.",
    "precio": 3900,
    "stock": 40,
    "imagen": "https://example.com/img/cinturon-fuerza.jpg",
    "categoria": "accesorios",
    "descuento": 10
  },
  {
    "id": 7,
    "marca": "Nike",
    "nombre": "Mancuerna Hexagonal 10kg",
    "descripcion": "Ideal para entrenamientos de fuerza e hipertrofia.",
    "precio": 9900,
    "stock": 25,
    "imagen": "https://example.com/img/mancuerna-10kg.jpg",
    "categoria": "mancuernas",
    "descuento": 10
  },
  {
    "id": 8,
    "marca": "Nike",
    "nombre": "Creatina Monohidratada 300g",
    "descripcion": "Mejora la fuerza y el rendimiento en entrenamientos intensos.",
    "precio": 4500,
    "stock": 60,
    "imagen": "https://example.com/img/creatina.jpg",
    "categoria": "suplementos",
    "descuento": 5
  },
  {
    "id": 9,
    "marca": "Nike",
    "nombre": "Shaker Mezclador 600ml",
    "descripcion": "Vaso mezclador con rejilla para batidos sin grumos.",
    "precio": 1200,
    "stock": 100,
    "imagen": "https://example.com/img/shaker.jpg",
    "categoria": "accesorios",
    "descuento": 0
  },
  {
    "id": 10,
    "marca": "Nike",
    "nombre": "Rodillera Deportiva Ajustable",
    "descripcion": "Protección y soporte para entrenamientos de pierna.",
    "precio": 2200,
    "stock": 45,
    "imagen": "https://example.com/img/rodillera.jpg",
    "categoria": "accesorios",
    "descuento": 5
  },
  {
    "id": 11,
    "marca": "Nike",
    "nombre": "Toalla de Mano Gym Pack x2",
    "descripcion": "Set de 2 toallas pequeñas para manos y rostro.",
    "precio": 1800,
    "stock": 80,
    "imagen": "https://example.com/img/toallas-mano.jpg",
    "categoria": "toallas",
    "descuento": 0
  },
  {
    "id": 12,
    "marca": "Nike",
    "nombre": "Proteína Vegana Vainilla 1kg",
    "descripcion": "Proteína vegetal ideal para veganos y alérgicos a lácteos.",
    "precio": 11000,
    "stock": 35,
    "imagen": "https://example.com/img/proteina-vegana.jpg",
    "categoria": "proteinas",
    "descuento": 15
  },
  {
    "id": 13,
    "marca": "Nike",
    "nombre": "Bandas de Resistencia Pack x5",
    "descripcion": "5 niveles de resistencia para entrenamientos funcionales.",
    "precio": 3500,
    "stock": 60,
    "imagen": "https://example.com/img/bandas.jpg",
    "categoria": "accesorios",
    "descuento": 10
  },
  {
    "id": 14,
    "marca": "Nike",
    "nombre": "Mancuerna Ajustable 20kg",
    "descripcion": "Sistema con discos intercambiables para variar el peso.",
    "precio": 21500,
    "stock": 15,
    "imagen": "https://example.com/img/mancuerna-ajustable.jpg",
    "categoria": "mancuernas",
    "descuento": 5
  },
  {
    "id": 15,
    "marca": "Puma",
    "nombre": "Guantes de Entrenamiento Mujer",
    "descripcion": "Diseño ergonómico para manos más pequeñas.",
    "precio": 2900,
    "stock": 40,
    "imagen": "https://example.com/img/guantes-mujer.jpg",
    "categoria": "guantes",
    "descuento": 0
  },
  {
    "id": 16,
    "marca": "Nike",
    "nombre": "L-Carnitina Líquida 500ml",
    "descripcion": "Suplemento para quema de grasa y energía.",
    "precio": 7200,
    "stock": 28,
    "imagen": "https://example.com/img/lcarnitina.jpg",
    "categoria": "suplementos",
    "descuento": 10
  },
  {
    "id": 17,
    "marca": "Nike",
    "nombre": "Proteína Isolate Frutilla 1kg",
    "descripcion": "Alta pureza, ideal para después del entrenamiento.",
    "precio": 12500,
    "stock": 20,
    "imagen": "https://example.com/img/proteina-isolate.jpg",
    "categoria": "proteinas",
    "descuento": 20
  },
  {
    "id": 18,
    "marca": "Nike",
    "nombre": "Toalla XL Secado Rápido",
    "descripcion": "Tamaño grande para cubrir bancas o usar como alfombra.",
    "precio": 3200,
    "stock": 25,
    "imagen": "https://example.com/img/toalla-xl.jpg",
    "categoria": "toallas",
    "descuento": 5
  },
  {
    "id": 19,
    "marca": "Nike",
    "nombre": "Cuerda para Saltar Profesional",
    "descripcion": "Cuerda con rodamientos para mayor velocidad.",
    "precio": 2400,
    "stock": 50,
    "imagen": "https://example.com/img/cuerda-saltar.jpg",
    "categoria": "accesorios",
    "descuento": 0
  },
  {
    "id": 20,
    "marca": "Nike",
    "nombre": "Mancuerna Vinilo 3kg (Par)",
    "descripcion": "Recubrimiento suave y colores vivos.",
    "precio": 4600,
    "stock": 35,
    "imagen": "https://example.com/img/mancuerna-vinilo.jpg",
    "categoria": "mancuernas",
    "descuento": 5
  },
    {
    "id": 21,
    "marca": "Nike",
    "nombre": "Disco Olímpico 10kg Goma",
    "descripcion": "Disco de entrenamiento con cubierta de goma para absorción de impacto.",
    "precio": 8800,
    "stock": 20,
    "imagen": "https://example.com/img/disco-10kg.jpg",
    "categoria": "discos",
    "descuento": 10
  },
  {
    "id": 22,
    "marca": "Nike",
    "nombre": "Barra Olímpica 20kg",
    "descripcion": "Barra profesional con rodamientos y agarre moleteado.",
    "precio": 26000,
    "stock": 10,
    "imagen": "https://example.com/img/barra-olimpica.jpg",
    "categoria": "barras",
    "descuento": 5
  },
  {
    "id": 23,
    "marca": "Nike",
    "nombre": "Botella Térmica Acero 750ml",
    "descripcion": "Botella térmica para mantener tu bebida fría o caliente.",
    "precio": 3400,
    "stock": 60,
    "imagen": "https://example.com/img/botella-termica.jpg",
    "categoria": "accesorios",
    "descuento": 0
  },
  {
    "id": 24,
    "marca": "Nike",
    "nombre": "Proteína Mass Gainer 3kg",
    "descripcion": "Ideal para ganancia de masa muscular rápida.",
    "precio": 16000,
    "stock": 15,
    "imagen": "https://example.com/img/mass-gainer.jpg",
    "categoria": "proteinas",
    "descuento": 15
  },
  {
    "id": 25,
    "marca": "Nike",
    "nombre": "Muslera de Compresión",
    "descripcion": "Soporte para muslos con ajuste de velcro.",
    "precio": 2800,
    "stock": 35,
    "imagen": "https://example.com/img/muslera.jpg",
    "categoria": "accesorios",
    "descuento": 0
  },
  {
    "id": 26,
    "marca": "Nike",
    "nombre": "Rueda Abdominal Doble",
    "descripcion": "Rueda para fortalecer core, abdominales y hombros.",
    "precio": 3300,
    "stock": 40,
    "imagen": "https://example.com/img/rueda-abdominal.jpg",
    "categoria": "accesorios",
    "descuento": 10
  },
  {
    "id": 27,
    "marca": "Nike",
    "nombre": "BCAA 2:1:1 300g",
    "descripcion": "Aminoácidos esenciales para recuperación muscular.",
    "precio": 6900,
    "stock": 30,
    "imagen": "https://example.com/img/bcaa.jpg",
    "categoria": "suplementos",
    "descuento": 10
  },
  {
    "id": 28,
    "marca": "Nike",
    "nombre": "Cinturón Lumbar Powerlifting",
    "descripcion": "Máxima rigidez para levantamientos pesados.",
    "precio": 7100,
    "stock": 18,
    "imagen": "https://example.com/img/cinturon-power.jpg",
    "categoria": "accesorios",
    "descuento": 15
  },
  {
    "id": 29,
    "marca": "Nike",
    "nombre": "Pesa Rusa 12kg",
    "descripcion": "Kettlebell ideal para entrenamiento funcional y fuerza.",
    "precio": 7400,
    "stock": 22,
    "imagen": "https://example.com/img/pesa-rusa-12kg.jpg",
    "categoria": "mancuernas",
    "descuento": 5
  },
  {
    "id": 30,
    "marca": "Nike",
    "nombre": "Tensor Elástico Rehabilitación",
    "descripcion": "Banda elástica suave para recuperación y estiramientos.",
    "precio": 1900,
    "stock": 55,
    "imagen": "https://example.com/img/tensor.jpg",
    "categoria": "accesorios",
    "descuento": 0
  },
  {
    "id": 31,
    "marca": "Nike",
    "nombre": "Pre-Entreno Nitro Boost 300g",
    "descripcion": "Aumenta el foco, energía y rendimiento.",
    "precio": 8400,
    "stock": 25,
    "imagen": "https://example.com/img/preentreno.jpg",
    "categoria": "suplementos",
    "descuento": 20
  },
  {
    "id": 32,
    "marca": "Nike",
    "nombre": "Guantes de Ciclismo/Gym con Gel",
    "descripcion": "Mayor protección en palma y agarre suave.",
    "precio": 2700,
    "stock": 40,
    "imagen": "https://example.com/img/guantes-gel.jpg",
    "categoria": "guantes",
    "descuento": 0
  },
  {
    "id": 33,
    "marca": "Nike",
    "nombre": "Toalla con Bolsillo Oculto",
    "descripcion": "Ideal para guardar llaves o celular mientras entrenás.",
    "precio": 3100,
    "stock": 40,
    "imagen": "https://example.com/img/toalla-bolsillo.jpg",
    "categoria": "toallas",
    "descuento": 5
  },
  {
    "id": 34,
    "marca": "Nike",
    "nombre": "Disco Olímpico Fraccional 2.5kg",
    "descripcion": "Disco de precisión para progresión de cargas.",
    "precio": 3500,
    "stock": 30,
    "imagen": "https://example.com/img/disco-fraccional.jpg",
    "categoria": "discos",
    "descuento": 0
  },
  {
    "id": 35,
    "marca": "Nike",
    "nombre": "Mat Fitness Antideslizante",
    "descripcion": "Superficie texturizada para mejor agarre durante ejercicios de piso.",
    "precio": 4700,
    "stock": 38,
    "imagen": "https://example.com/img/mat-fitness.jpg",
    "categoria": "accesorios",
    "descuento": 10
  },
  {
    "id": 36,
    "marca": "Adidas",
    "nombre": "Proteína Hidrolizada Café 1kg",
    "descripcion": "Rápida absorción, ideal para recuperación post entreno.",
    "precio": 13200,
    "stock": 18,
    "imagen": "https://example.com/img/proteina-cafe.jpg",
    "categoria": "proteinas",
    "descuento": 20
  },
  {
    "id": 37,
    "marca": "Nike",
    "nombre": "Gorra Running Secado Rápido",
    "descripcion": "Protección solar con tejido respirable.",
    "precio": 2600,
    "stock": 42,
    "imagen": "https://example.com/img/gorra-running.jpg",
    "categoria": "accesorios",
    "descuento": 5
  },
  {
    "id": 38,
    "marca": "Nike",
    "nombre": "Espuma Foam Roller Texturado",
    "descripcion": "Para automasajes y recuperación muscular.",
    "precio": 3900,
    "stock": 35,
    "imagen": "https://example.com/img/foam-roller.jpg",
    "categoria": "accesorios",
    "descuento": 10
  },
  {
    "id": 39,
    "marca": "Nike",
    "nombre": "Short Deportivo Hombre Secado Rápido",
    "descripcion": "Short liviano y cómodo para entrenamiento o running.",
    "precio": 4100,
    "stock": 45,
    "imagen": "https://example.com/img/short-hombre.jpg",
    "categoria": "ropa",
    "descuento": 10
  },
  {
    "id": 40,
    "marca": "Nike",
    "nombre": "Remera Técnica Mujer DryFit",
    "descripcion": "Remera con tecnología DryFit para mayor frescura.",
    "precio": 3600,
    "stock": 50,
    "imagen": "https://example.com/img/remera-mujer.jpg",
    "categoria": "ropa",
    "descuento": 10
  }
]
